### ISSUE TITLE
User Manual

### ISSUE THREAD

**Issue by thevirtuoso1973** [UCLComputerScience/COMP0016_2020_21_Team26#128]
Document how to use the app. The format could be in Markdown or a Word document on Teams that we could export to PDF.

**Comment by thevirtuoso1973** [comment]
Maybe we could add the usage guide to the Wiki, word docs are pretty old fashioned.

**Comment by saachipahwa** [comment]
Sure, I finished it and added it to the wiki

**Comment by thevirtuoso1973** [comment]
Looks good although I just remembered we'll have to submit the manual in a zip file so we'll need a PDF copy as well.
